[package]
name = "crosscut-game-engine"
edition = "2021"

[dependencies]
num_enum = "*"
serde = "*"
serde-big-array = "*"

[dependencies.crosscut-compiler]
path = "../compiler"

[dependencies.crosscut-runtime]
path = "../runtime"
