[package]
name = "crosscut-runtime"
edition = "2021"

[dependencies.serde]
version = "*"
default-features = false
features = ["alloc", "derive"]

[dependencies.thiserror]
version = "*"
default-features = false

[dependencies.udigest]
version = "*"
features = ["derive"]
