[workspace]

[package]
name = "crosscut"
edition = "2021"

[dependencies]
anyhow = "*"
crossbeam-channel = "*"
crossterm = "*"
pollster = "*"
thiserror = "*"
wgpu = "*"
winit = "*"

[dependencies.udigest]
version = "*"
features = ["derive"]
