name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Run website builder
        run: cargo run --package website

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: crosscut
          entrypoint: server/main.tsx
          root: website-output
