name: Deploy

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            # GitHub Actions ships Rust by default, but there might be a delay
            # when a new Rust version is out. This actions is based on rustup,
            # so we can always get whatever the Rust project released.
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: Run website builder
              run: cargo run --package website

            - name: Deploy to Deno Deploy
              uses: denoland/deployctl@v1
              with:
                  project: crosscut
                  entrypoint: server/main.tsx
                  root: website-output
